### PR TITLE
improved nginx-reload.sh script

### PR DESCRIPTION
**Pull request by gytisgreitai**
1. Added log() function which logs events with timestamp, adds `nginx` prefix, optionally into stderr
2. Added debounce so that we would not get multiple reloads (source: https://stackoverflow.com/a/12807105/911849) 
3. Added option NGINX_CONFIG_FILE which allows you to specify custom config file to test (`-t`) by default tests /etc/nginx/nginx.conf
4. Added recursive option into inotifywait (usefull if you have couple of ssl certs mounted e.g. in /etc/nginx/ssl

### CODE REVIEW

**Comment by gytisgreitai** [comment]
darn, i Alos changed `WATCH_PATHS` -> `NGINX_WATCH_PATHS` so will need to update the docs. But not sure if you are still keeping an eye on this, and if you will want to merge this.

**Comment by rosskukulinski** [comment]
Hi @gytisgreitai!  I wasn't watching my own repo (doh!) so I missed this PR.  Thanks for the submission - looks like great improvements and I looking forward to taking it for a spin (and merge!).

If you have a few minutes, updating the docs for the rename of `WATCH_PATHS` would be greatly appreciated.

**Comment by gytisgreitai** [comment]
sorry about delay,  I've been a little busy:( Will fix the docs tomorrow

**Comment by dvaldivia** [comment]
I like this PR, it should be merged :P

**Pull request merged**
